version: '3.9'

services:

  mysql:
    image: mysql:8.0
    container_name: pi-univesp

    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pi-univesp
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: